- name: Set community repositories and update
  hosts: all

  tasks:
    - name: Install qemu-guest-agent
      ansible.builtin.apt:
        name:
          - qemu-guest-agent
        state: present

    - name: Start qemu-guest-agent.service
      ansible.builtin.systemd_service:
        name: qemu-guest-agent
        state: started
